name       : python-stem
version    : 1.8.0
release    : 4
source     :
    - https://pypi.io/packages/source/s/stem/stem-1.8.0.tar.gz : a0b48ea6224e95f22aa34c0bc3415f0eb4667ddeae3dfb5e32a6920c185568c2
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python controller library for Tor
description: |
    Stem is a Python controller library for Tor. With it you can use Tor control protocol to script against the Tor process, or build things such as Nyx.
build      : |
    %python3_setup
install    : |
    %python3_install
