name       : python-stem
version    : 1.6.0
release    : 1
source     :
    - https://pypi.python.org/packages/11/d5/e51983f81b38408ae2f0e166481ad867962f6fa07610fe71119534e12d41/stem-1.6.0.tar.gz : d7fe1fb13ed5a94d610b5ad77e9f1b3404db0ca0586ded7a34afd323e3b849ed
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Python controller library for Tor
description: |
    Stem is a Python controller library for Tor. With it you can use Tor control protocol to script against the Tor process, or build things such as Nyx.
build      : |
    %python3_setup
install    : |
    %python3_install
